name: Build and Push FridgeNotes

on:
  push:
    branches: [ main, master, Shared-Notes-Hiding, drag-n-drop-fixes ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'fridgenotes-frontend/package-lock.json'
      
    - name: Install frontend dependencies
      run: |
        cd fridgenotes-frontend
        npm ci
        
    - name: Build frontend
      run: |
        cd fridgenotes-frontend
        npm run build
        
    - name: Verify build output
      run: |
        echo "Build completed. Contents of src/static:"
        ls -la src/static/
      
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
    - name: Set image tag based on branch
      id: tag
      run: |
        if [[ "${GITHUB_REF_NAME}" == "main" || "${GITHUB_REF_NAME}" == "master" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          BRANCH_TAG=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')
          echo "tag=${BRANCH_TAG}" >> $GITHUB_OUTPUT
        fi
      
    - name: Build and push Docker image
      run: |
        IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/fridgenotes"
        docker build --no-cache \
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
          --label "org.opencontainers.image.url=https://github.com/${{ github.repository }}" \
          --label "org.opencontainers.image.documentation=https://github.com/${{ github.repository }}" \
          --label "org.opencontainers.image.title=FridgeNotes" \
          --label "org.opencontainers.image.description=Self-hosted note-taking application with real-time collaboration" \
          --label "org.opencontainers.image.vendor=${{ github.repository_owner }}" \
          --label "org.opencontainers.image.version=${{ steps.tag.outputs.tag }}" \
          --label "org.opencontainers.image.revision=${{ github.sha }}" \
          --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          -t ${IMAGE_TAG}:${{ steps.tag.outputs.tag }} \
          -t ${IMAGE_TAG}:${{ github.sha }} \
          .
        docker push ${IMAGE_TAG}:${{ steps.tag.outputs.tag }}
        docker push ${IMAGE_TAG}:${{ github.sha }}